name: md4
version: 0.1.0
author: Thomas Down <thomas@biodalliance.org>
description: Pure-Dart implementation of the MD4 hash function
homepage: https://github.com/dasmoth/md4
dev_dependencies:
  unittest: any

#dependencies:
#  unittest: any